### ISSUE TITLE
Not showing rational message

### ISSUE THREAD

**Issue by bitamirshafiee** [nabinbhandari/Android-Permissions#25]
Hi,
I have version 3.8
the first time I require the permission message is not showing but from the second time message is showing on all requests.
and on some devices not showing the rational message at all.
I am using kotlin by the way.

**Comment by nabinbhandari** [comment]
Not showing permission rationale on the first request and showing rationale after the permission has been denied once, is the expected behavior. If a permission has never been asked before, the method `shouldShowRequestPermissionRationale(...)` returns false.

I will need more information on your comment on the dialog not being shown at all on some devices. Also, please check if the behavior of this library is different from the behavior of the code in the [official tutorial](https://developer.android.com/training/permissions/requesting).
