### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by missrasdiana** [nabinbhandari/Android-Permissions#4]
Hi, i use your library in my library project and it works well. But, when i generate my library into aar format, and then included it to my app project, it does not work.
I've found this error >> java.lang.ClassNotFoundException: Didn't find class "com.nabinbhandari.android.permissions.PermissionHandler"

Thank you

**Comment by nabinbhandari** [comment]
Hello,

To build the AAR file, follow the instructions below:

- Checkout the repository.
- Run the task 'assembleRelease' of module 'permissions' in Gradle.
- Locate the AAR file in the directory build/outputs/aar.
- Use the AAR file as dependency in your project instead of gradle dependency.

Make sure that you haven't enabled proguard while building the AAR file. You can enable it in your app while building APK file though.
